import PropTypes from 'prop-types';
import Logo from './components/Logo';
import Navigation from './components/Navigation';
import './globals.css';

export const metadata = {
  title: 'The Wild Oasis',
  description: 'Generated by create next app and ECR dev',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <header>
          <Logo />
        </header>
        <Navigation />
        <main>{children}</main>
        <footer>Copyright by the Wild Oasis</footer>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
